### PR TITLE
[OSCD] regini LOLBAS 

### PR DESCRIPTION
**Pull request by SanWieb**
Detects the execution of regini.exe.

As far as I know is it not possible to check if there is read from an ADS (unlike the creation of an ADS: Event ID 15), so there is only a detection for the general case.

#1014

### CODE REVIEW

**Comment by aw350m33d** [comment]
I think reading from ADS can be detected using a regular expression. But it seems to me that for LOLBINs it is not so important where the file is read from. 

Actually, it seems to me that we can create a separate rule that will trigger on the path to ADS in the command line. This can solve the problems of all rules that have interactions with ADS. What do you think?

**Comment by SanWieb** [comment]
Separate rule for ADS would be better indeed. 

First I thought we could advance of the fact that it is not allowed to have a `:` in a filename, so if there is a string with 2 times ':' it has to be an ADS.  But we would miss the case if the imported file is not accessed with the driveletter (for example with `.\file:file`)

This would be better, agree?:

```
  - CommandLine|re: ':[^ \\]'
```
Importing from an ADS tree is very suspicious, isn't it? An rule level of high would be appropriate in my opinion.

**Comment by aw350m33d** [comment]
Yup! This is a very elegant approach. This regex will solve the problem. Perfect solution! 👍🏻 

And yes, I can't imagine a legitimate scenario where someone runs a command with a path containing an ADS component. Very suspicious activity.

**Comment by yugoslavskiy** [comment]
Hello @SanWieb! Thank you for your contribution (: Great job!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Comment by SanWieb** [comment]
Thanks @yugoslavskiy!

I will make tomorrow the last adjustment with the ADS regex, after that it can be merged. I will sent a comment in here.

**Comment by SanWieb** [comment]
Done!

**Comment by aw350m33d** [comment]
Perfect! Then it can be merged! 🥳

**Pull request merged**
