### PR TITLE
[OSCD] T1016: System Network Configuration Discovery - Linux

### PR DESCRIPTION
**Pull request by omergunal**
https://github.com/Neo23x0/sigma/issues/1011

Task 2

### CODE REVIEW

**Comment by zinint** [comment]
Hello and welcome!

Please help me to understand, are you planning to detect those via audit.d with the rule that's smth like this: (?)
``` bash
-a exit,always -F arch=b32 -S execve -k auditcmd
```
Then you should probably use some additional `{field: value}` in your detection, e.g.
``` YAML
service: auditd
detection:
    selection:
        type: 'EXECVE'
        a0: 'ifconfig'
```
for example, like here `rules\linux\auditd\lnx_auditd_susp_cmds.yml` or `here rules\linux\auditd\lnx_network_sniffing.yml`

What do you think? Did you run some tests? What did they show?

**Comment by zinint** [comment]
Hello again @omergunal, we had discussed this a bit and decided that your format of describing EXECVE type of detection is better, simply by using `Commands|contains` instead of using `a0`, `a1`, etc. But you should add a `category` value `process_creation` to your rules in PRs #1078, #1079, and #1083.

About this particular PR:
1. ` rules/linux/lnx_system_network_config_discovery.yml` - it's corresponding a bit with an existing rule `rules\linux\lnx_shell_priv_esc_prep.yml`, but I think it's ok. Let's see what the community will say after you'll add a `category`.
2. `rules/windows/registry_event/sysmon_comhijack_sdclt.yml` - you already put this rule in PRs #1078, #1079, #1082 and #1083, and I already commented on it [there](https://github.com/Neo23x0/sigma/pull/1078#issuecomment-707334832). Please decide where you'll leave it and delete the other ones.

**Comment by zinint** [comment]
Thanks for the update!

But you didn't do anything with the second rule in every one of your PRs `rules/windows/registry_event/sysmon_comhijack_sdclt.yml`:
1. Will you remake your PRs or leave it in everyone anyway?
2. Will you change the rule's `detection` according to the test wich [I described here](https://github.com/Neo23x0/sigma/pull/1078#issuecomment-707334832).

**Comment by yugoslavskiy** [comment]
Hello @omergunal , @remotephone! Guys, it seems that you both developed a Linux rule for T1016. 
And I believe that they could be merged. Could you please work it out together, editing a rule that was already approved (https://github.com/Neo23x0/sigma/pull/1086)?

It also makes sense to check if there are other intersections in your work.

Thank you!

**Comment by remotephone** [comment]
I think this should be covered in https://github.com/remotephone/sigma/commit/8f6ce25bab4cb137d469e63339ec1a8616a01f06 and https://github.com/remotephone/sigma/commit/48cabeafe5ca5a05ec89bd54324504243b88cac9. If you have any comments or suggestions @omergunal, please let me know. Thanks!

**Comment by yugoslavskiy** [comment]
Hello @omergunal @remotephone could you guys agree on the next steps for these rules? You can resolve this the same way we did it here: https://github.com/Neo23x0/sigma/pull/1056

**Comment by omergunal** [comment]
https://github.com/Neo23x0/sigma/pull/1086

**Pull request closed without merging**
