### PR TITLE
Create win_pass_the_hash.yml

### PR DESCRIPTION
**Pull request by iliaselmatani**
Rule to detects the attack technique pass the hash which is used to move laterally inside the network

### CODE REVIEW

**Comment by Neo23x0** [comment]
Sorry, but this matches on almost any LogonType:3 event of ID 4624 and 4625. The rule would trigger on to many events.

**Comment by iliaselmatani** [comment]
@Neo23x0 thanks for the review. I understand that LogonType:3 event of ID 4624 and 4625 would matches on almost anything therefore added the lines below for a better match.

```
LogonProcess: 'NtLmSsp'
KeyLength: '0'
```
Could you please review again?

**Comment by Neo23x0** [comment]
I did. 
That's normal logon behaviour. It's indistinguishable from normal LogonType:3 logons. 

What we could create is a rule that uses placeholders like %Workstations% in Computername and %Workstations% in WorkstationName to detect network logons between Workstations.

**Comment by iliaselmatani** [comment]
Hi @Neo23x0, based on your review I have added placeholders for WorkstationName to detect network logons between Workstations. Didn't find the field 'Computername' in the events. That's why I did not add a placeholder for that field.

**Comment by Neo23x0** [comment]
The ComputerName is the name of the host that generates the event. The WorkstationName is the name of the connecting source. Combined we can use the rule to detect logon behaviour between Workstations, which is suspicious.

**Pull request merged**
