### PR TITLE
[OSCD] Suspicious ftp.exe usage (LOLBin)

### PR DESCRIPTION
**Pull request by stvetro**
Tasks 45 #1014  
ftp.exe

### CODE REVIEW

**Comment by aw350m33d** [comment]
Hello Victor! Thank you very much for your contribution to the initiative!

We ask all participants to create separate PRs for each rule, especially if they are from different tasks. This helps us a lot in the review and merge process.
It was in this comment:
   https://github.com/Neo23x0/sigma/issues/1014#issuecomment-702470329
And also on the site (`How to add your contribution for a review` section):
  https://oscd.community/sprints/sprint_2_howto.html 

Could you make a separate PR for each rule?

**Comment by stvetro** [comment]
> 
> 
> Hello Victor! Thank you very much for your contribution to the initiative!
> 
> We ask all participants to create separate PRs for each rule, especially if they are from different tasks. This helps us a lot in the review and merge process.
> It was in this comment:
> [#1014 (comment)](https://github.com/Neo23x0/sigma/issues/1014#issuecomment-702470329)
> And also on the site (`How to add your contribution for a review` section):
> https://oscd.community/sprints/sprint_2_howto.html
> 
> Could you make a separate PR for each rule?

Done =)

**Comment by yugoslavskiy** [comment]
Thank you very much for your contribution, @stvetro! Great job!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
