### PR TITLE
[OSCD] winrm.vbs_2

### PR DESCRIPTION
**Pull request by Vasilisa-L**
winrm.vbs LOLbas #1014

### CODE REVIEW

**Comment by aw350m33d** [comment]
Honestly, it seems to me that it doesn't matter which process is the parent of `winrm`. 
Are there any reasons to believe that the parent is `cscript.exe` only?

**Comment by Vasilisa-L** [comment]
> Honestly, it seems to me that it doesn't matter which process is the parent of `winrm`.
> Are there any reasons to believe that the parent is `cscript.exe` only?

@aw350m33d 
Anton
I tried to launch winrm.vbs with wscript.exe
I got following error message:
Error

Any other ideas?

**Comment by aw350m33d** [comment]
Wow! This feature is really hardcoded in the code of this script.

image

So, I think this rule can be considered complete and can be merged. @yugoslavskiy

**Comment by yugoslavskiy** [comment]
Thank you, @Vasilisa-L ! Great job (:

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
