### PR TITLE
[OSCD] Sqldumper.exe LOLbin

### PR DESCRIPTION
**Pull request by zBlurr**
task 129. Sqldumper.exe #1014

### CODE REVIEW

**Comment by aw350m33d** [comment]
Hi, Kirill! Thank you so much for continuing to participate in the initiative for the second year! 💪🏻 

Unfortunately, you accidentally pushed the rule from another PR. 🙈 
Could you remove it from this branch and re-push the changes? 😃

**Comment by aw350m33d** [comment]
So much better! 👍🏻 
But why did you put the tags `attack.t1003` and `attack.t1003.001` at the same time? 
Usually, a tag is put without sub-technique if there is no suitable sub-technique yet. But you chose one. 
Is this a typo or is there a reason?

**Comment by zBlurr** [comment]
I've been waiting for this for a whole year 👍 I've put 2 tags, because any process can be dumped, not only lsass

**Comment by aw350m33d** [comment]
Oh, ok. I understood the logic of your reasoning. 👌🏻 
But the rest of the sub-techniques in this category are not about dumping processes. Therefore, I would suggest leaving only the `lsass memory` sub-technique.

**Comment by zBlurr** [comment]
I think, you are right, Anton. I've removed this tag.

**Review by aw350m33d — APPROVED** [review]
I think it's ready for merge @yugoslavskiy

**Comment by yugoslavskiy** [comment]
Hello @zBlurr! Thank you for your contribution!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
