### PR TITLE
Split rules based on Sysmon event ID

### PR DESCRIPTION
**Pull request by stevengoossensB**
The sysmon rules are grouped by category, which is mapped to the Sysmon EventID in the sysmon.yml config file. The eventIDs are deleted from the rules and replaced by a category.

Automated testing fails on some checks because there is a check for EventID being in the rule.

### CODE REVIEW

**Comment by Neo23x0** [comment]
I'm on vacation and cannot help a lot. I think we have to remove the `service: sysmon` from all the rules.

**Comment by Neo23x0** [comment]
@thomaspatzke : Can you check that pull request? I think it would be great to get all Sysmon events into these generic categories. I just don't have a good oversight on the required adjustments in the mapping configs.

**Comment by Neo23x0** [comment]
Or - let me try to modify that pull request

**Comment by thomaspatzke** [comment]
Great pull request! Done some tests and seems fine to me, merged! Thanks @stevengoossensB!

**Pull request merged**
