### PR TITLE
[OSCD] Presentationhost.exe LOLbin

### PR DESCRIPTION
**Pull request by zBlurr**
task 67. Presentationhost.exe #1014

### CODE REVIEW

**Comment by aw350m33d** [comment]
Nice rule! 加油加油! 💪🏻 

I think it's ready for merge! @yugoslavskiy

**Comment by zBlurr** [comment]
Hello Anton, thank you.

**Review by aw350m33d — APPROVED** [review]
I think it's ready for merge

**Comment by yugoslavskiy** [comment]
Hello @zBlurr! The rule looks perfect. Thank you very much!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
