### PR TITLE
[OSCD] Added a rule to detect potential persistence using registry keys

### PR DESCRIPTION
**Pull request by V3T0**
Added a rule to detect potential persistence using registry keys

### CODE REVIEW

**Comment by V3T0** [comment]
Hi @yugoslavskiy, I rebased my repo and still I'm having the same problem. What should I do now? :/

**Comment by yugoslavskiy** [comment]
Hey @V3T0! Good question. Let's try to get help from @thomaspatzke (: could you please advise on the next steps?

**Comment by yugoslavskiy** [comment]
Hello @V3T0! There is a guy that successfully fixed the issue in his PR https://github.com/Neo23x0/sigma/pull/1257

I hope that it will help you to adjust your PR and pass the test (:

**Comment by zinint** [comment]
> 
> 
> Hello @V3T0! There is a guy that successfully fixed the issue in his PR #1257
> 
> I hope that it will help you to adjust your PR and pass the test (:

I'd like to add a bit more context in hope that it will help you.

Basically you should cherry pick [this commit](https://github.com/Neo23x0/sigma/commit/31241d9bbdde78575293ec97da83e193b902b47c).

In order to do this you should use Git CLI, smth like this:
```
git clone `your fork`
cd `your fork`
git remote add originalSigma https://github.com/Neo23x0/sigma
git remote -v
git fetch originalSigma
git cherry-pick 31241d9bbdde78575293ec97da83e193b902b47c
git push -u origin
```

And then just rebase.
Hope that'll help, best regards!

**Comment by yugoslavskiy** [comment]
Hello @V3T0! Could you please rebase your rule following the [example](https://github.com/Neo23x0/sigma/pull/1286#issuecomment-729894829) provided by @zinint?  (:

**Comment by yugoslavskiy** [comment]
Thank you for your contribution, @V3T0!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
