### PR TITLE
[OSCD] Detects Obfuscated Powershell via use Rundll32 in Scripts #30 (process_creation) 

### PR DESCRIPTION
**Pull request by NikitaStormwind**
Made it a single regular expression.
In the first version (?i).?cmd./c\s*"set\s+.*downloadstring&&.rundll32.powershell.(value|invoke|comspec|iex)." , but I changed it because the script can be of this type:
'Invoke-Expression (New-Object Net.WebClient).DownloadString&&RuNdll32 SHELL32.DLL ShellExec_RunDLL "PoWERsheLl" " -noPRoFIL " " ( ^& ( '{1}{2}{3}{0}' -f 'eM','GE','t-child','IT' ) ( '{0}{1}' -f'E','nV:igFm' ) ).'VAlUE' ^| . ( '{1}{0}'-f 'x','ie')"'
And i add in regular 'iex' because 'invoke' could be different.

### CODE REVIEW

**Comment by zinint** [comment]
Issue #1009 (useful link to see this PR in the Issue)))

Because our goal is to detect the obfuscation method looking for similar patterns in all of it obfuscation examples, I'd suggest dropping `downloadstring` & `powershell`, and focus on other patterns. Your regex, as a result, could look smth like this:
``` REGEXP
(?i).*&&.*rundll32.*shell32\.dll.*shellexec_rundll.*(value|invoke|comspec|iex).*"
```  

More to the point, because **one obfuscation method = 3 Sigma rules** (see the end of the Issue) can you please be so kind and create the 3rd rule for service creation events for that Task?

**Comment by NikitaStormwind** [comment]
> Issue #1009 (useful link to see this PR in the Issue)))
> 
> Because our goal is to detect the obfuscation method looking for similar patterns in all of it obfuscation examples, I'd suggest dropping `downloadstring` & `powershell`, and focus on other patterns. Your regex, as a result, could look smth like this:
> 
> ```regexp
> (?i).*&&.*rundll32.*shell32\.dll.*shellexec_rundll.*(value|invoke|comspec|iex).*"
> ```
> 
> More to the point, because **one obfuscation method = 3 Sigma rules** (see the end of the Issue) can you please be so kind and create the 3rd rule for service creation events for that Task?

Ok, no problem. Tomorrow I'll edit the rule and create a third Sigma rule

**Comment by zinint** [comment]
That'll be super cool! Thanks again and have a nice evening!

**Comment by NikitaStormwind** [comment]
> > Issue #1009 (useful link to see this PR in the Issue)))
> > Because our goal is to detect the obfuscation method looking for similar patterns in all of it obfuscation examples, I'd suggest dropping `downloadstring` & `powershell`, and focus on other patterns. Your regex, as a result, could look smth like this:
> > ```regexp
> > (?i).*&&.*rundll32.*shell32\.dll.*shellexec_rundll.*(value|invoke|comspec|iex).*"
> > ```
> > 
> > 
> > More to the point, because **one obfuscation method = 3 Sigma rules** (see the end of the Issue) can you please be so kind and create the 3rd rule for service creation events for that Task?
> 
> Ok, no problem. Tomorrow I'll edit the rule and create a third Sigma rule

Done

**Comment by yugoslavskiy** [comment]
Hello @NikitaStormwind! Thank you for your continuous contribution. Great job!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
