### PR TITLE
[OSCD] LOLBAS Setupapi.yml

### PR DESCRIPTION
**Pull request by grikos**
LOLBAS Setupapi.yml 100 in #1014

### CODE REVIEW

**Comment by aw350m33d** [comment]
I have a small question ( : 

Why are you looking for the launch of this particular program (RunOnce)? According to the description, this is only one of the possible cases. 

Did I understand the idea of your rule correctly?

**Comment by grikos** [comment]
During my experiments I realized that setupapi.dll runs "runonce.exe" executable regardles of actual contents of INF -file

https://twitter.com/Z3Jpa29z/status/1313742350292746241?s=20

**Comment by aw350m33d** [comment]
Excellent! Then I have no questions about this rule and it can be merged. @yugoslavskiy

**Comment by aw350m33d** [comment]
Good! Now it's ready to merge ( : 
@yugoslavskiy

**Comment by yugoslavskiy** [comment]
Thank you @grikos! Well done (:

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
