### PR TITLE
[OSCD] Detects Obfuscated Powershell via Stdin in Scripts #28 (Services)

### PR DESCRIPTION
**Pull request by NikitaStormwind**
#1009 - add Rule(3) Task 28

### CODE REVIEW

**Comment by zinint** [comment]
Hello again @NikitaStormwind (:
I'll check the rule and will get back to you!
Great job and pace BTW (:

**Comment by zinint** [comment]
Thanks again @NikitaStormwind !
@yugoslavskiy I believe that this PR could be merged (:

**Comment by yugoslavskiy** [comment]
Thank you, @NikitaStormwind!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
