### PR TITLE
Bloodhound rpc connections

### PR DESCRIPTION
**Pull request by savvyspoon**

### CODE REVIEW

**Comment by Neo23x0** [comment]
@thomaspatzke : That aggregation isn't possible, right? 
```
selection | CreationDate > -14d
```

**Comment by thomaspatzke** [comment]
No, this is something for a condition that is not yet implemented.

**Comment by Neo23x0** [comment]
Sorry, there is no backend support for that syntax. 
What do we do with these rules? @thomaspatzke 
Could we pull them into a branch with future supported aggregations?

**Comment by thomaspatzke** [comment]
Yes, we have a directory with not yet supported syntax elements that coule be supported in the future.

**Comment by savvyspoon** [comment]
Is it both of them or just the new domains?

**Pull request closed without merging**
