### PR TITLE
[OSCD] Created win_susp_wsl_lolbin.yml

### PR DESCRIPTION
**Pull request by svch0stz**
Part of oscd sprint 2 - https://github.com/Neo23x0/sigma/issues/1014

Testing:
`❯ python .\sigmac -t es-qs -c .\config\elk-windows.yml ..\rules\windows\process_creation\win_susp_wsl_lolbin.yml
(Image.keyword:(*\\wsl.exe) AND CommandLine.keyword:(*\ \-e\ * OR *\ \-\-exec\ *))`

`❯ python .\sigmac -t splunk -c .\config\splunk-windows.yml ..\rules\windows\process_creation\win_susp_wsl_lolbin.yml
((Image="*\\wsl.exe") (CommandLine="* -e *" OR CommandLine="* --exec *"))`

### CODE REVIEW

**Comment by aw350m33d** [comment]
Hello, Zach! 

Thanks for the active start of the sprint! Great job! I think this PR can be accepted. 
@Neo23x0 @thomaspatzke

**Comment by yugoslavskiy** [comment]
Hello @svch0stz ! 

Thank you for your contribution. 
The rule looks perfect. 
Would you mind adding "oscd.community" to the author field? 
It will help with the promotion of the initiative and engage more people in the next sprints.

Thank you again!

**Comment by svch0stz** [comment]
Thanks Dan! Sorry will update them now,

`author: 'oscd.community, Zach Stanford @svch0st'`

**Comment by yugoslavskiy** [comment]
> Thanks Dan! Sorry will update them now,
> 
> `author: 'oscd.community, Zach Stanford @svch0st'`

Thank you very much!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 I believe that this PR could be merged (: 
please let me know what do you think about it if there is anything you would like to change.

**Comment by thomaspatzke** [comment]
Nice one! Thanks for contribution!

**Pull request merged**
