### PR TITLE
[OSCD] Detects Obfuscated Powershell via WMIC Launcher #22 (4104, 4103 + Services + process_creation)

### PR DESCRIPTION
**Pull request by zinint**
#1009 task 22

### CODE REVIEW

**Comment by yugoslavskiy** [comment]
Hello @thomaspatzke! 
We are having problems with a regex that has to have both `'` and `"`:

```
ImagePath|re: '(?i).*wmic(?:\.exe)?(?:\s+)?(?:"|')?process(?:"|')?.*call.*create.*powershell'
```

Could you please suggest a solution for this scenario? Thanks!

**Comment by yugoslavskiy** [comment]
I think that [this construction](https://github.com/Neo23x0/sigma/pull/1230#discussion_r508750374) will solve this. @zinint what do you think?

**Comment by zinint** [comment]
Hey, thanks @yugoslavskiy I'll try this and will get back to you!

**Comment by zinint** [comment]
@zinint thanks, it helped! But now [I'm stuck here](https://github.com/Neo23x0/sigma/pull/1230#issuecomment-722931666) ((:

**Comment by yugoslavskiy** [comment]
I think that the rule is ready anyway (: Thank you very much, mate! Well done!

**Review by yugoslavskiy — DISMISSED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Comment by yugoslavskiy** [comment]
Hey @zinint! Now it seems that your rule has been lost, I can't find it in the "Files changed" section %)

**Pull request closed without merging**
