### PR TITLE
[OSCD] winrm.vbs_1

### PR DESCRIPTION
**Pull request by Vasilisa-L**
AWL Bypass with Winrm.vbs, copied cscript.exe and malicious WsmPty.xsl/WsmTxt.xsl
#1014

### CODE REVIEW

**Comment by aw350m33d** [comment]
Julia, great rule! 

Additionally, I have a suggestion.
This rule does not analyze activity with `WsmPty.xsl` or `WsmTxt.xsl` files. Maybe we will make a [rule collection](https://github.com/Neo23x0/sigma/wiki/Specification#rule-collections) from this rule with a section about creating files (`file_event` category) WsmPty.xsl or WsmTxt.xsl in non-standard places (example https://github.com/Neo23x0/sigma/blob/master/rules/windows/file_event/sysmon_webshell_creation_detect.yml)?

If necessary, you can read more about rule collections [here](https://habr.com/ru/company/pt/blog/515532)

**Comment by Vasilisa-L** [comment]
@aw350m33d 

I made rule collection
Now it's much better and has more logic
I really appreciate your contribution in this project and my rules especially :)

**Comment by aw350m33d** [comment]
Great job! 
Now, this rule looks much clearer and more complete. This rule can be merged. @yugoslavskiy 

@Vasilisa-L thank you for such kind words, it's like a fuel!

**Comment by yugoslavskiy** [comment]
Thank you very much @Vasilisa-L ! (:

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
