### PR TITLE
Added Azure Log Analytics Backend

### PR DESCRIPTION
**Pull request by tuckner**
Added support for Azure Log Analytics to be able to generate queries for the Windows Security log and Sysmon.  Security is parsed natively by Azure Log Analytics, but Sysmon is not so the additional 'parse' argument needs to be added to each query in order to create searchable fields when the query is ran.  The fields are produced by referencing a Sysmon schema given in the contrib folder (v7, v8, v9, etc). It should be noted that this file should be updated with the version of Sysmon in use.  Useful schema files can be found here:

v9: https://gist.github.com/olafhartong/f2c114b9a69cd8a67dda48a53f959f2b
v8: https://gist.github.com/olafhartong/761f471865e7d1c66fbb27d2e5ffa9f0
v7: https://gist.github.com/olafhartong/28fad04686c1e03de2673c9382f46b93

```
$ python3 tools/sigmac -t ala rules/windows/sysmon/sysmon_dhcp_calloutdll.yml 
Event | parse EventData with * 'Data Name="RuleName">' RuleName '<' * 'Data Name="EventType">' EventType '<' * 'Data Name="UtcTime">' UtcTime '<' * 'Data Name="ProcessGuid">' ProcessGuid '<' * 'Data Name="ProcessId">' ProcessId '<' * 'Data Name="Image">' Image '<' * 'Data Name="TargetObject">' TargetObject '<' * 'Data Name="Details">' Details '<' *  | where (EventID == "13" and TargetObject endswith "\\Services\\DHCPServer\\Parameters\\CalloutDlls" or TargetObject endswith "\\Services\\DHCPServer\\Parameters\\CalloutEnabled")
```

```
$ python3 tools/sigmac -t ala rules/windows/sysmon/sysmon_susp_powershell_rundll32.yml 
Event | parse EventData with * 'Data Name="RuleName">' RuleName '<' * 'Data Name="UtcTime">' UtcTime '<' * 'Data Name="SourceProcessGuid">' SourceProcessGuid '<' * 'Data Name="SourceProcessId">' SourceProcessId '<' * 'Data Name="SourceImage">' SourceImage '<' * 'Data Name="TargetProcessGuid">' TargetProcessGuid '<' * 'Data Name="TargetProcessId">' TargetProcessId '<' * 'Data Name="TargetImage">' TargetImage '<' * 'Data Name="NewThreadId">' NewThreadId '<' * 'Data Name="StartAddress">' StartAddress '<' * 'Data Name="StartModule">' StartModule '<' * 'Data Name="StartFunction">' StartFunction '<' *  | where (EventID == "8" and SourceImage endswith "\\powershell.exe" and TargetImage endswith "\\rundll32.exe")
```

```
$ python3 tools/sigmac -t ala rules/windows/builtin/win_susp_lsass_dump.yml 
SecurityEvent | where (EventID == "4656" and ProcessName == "C:\Windows\System32\lsass.exe" and AccessMask == "0x705" and ObjectType == "SAM_DOMAIN")
```

### CODE REVIEW

**Comment by tuckner** [comment]
Also, these queries should work to create 'Custom Alert Rules' in Azure Security Center which run on defined schedules (ex. hourly) and send alerts if the queries find anything. Should be really great functionality.

screen shot 2019-03-04 at 11 23 56 am

**Comment by tuckner** [comment]
@thomaspatzke @Neo23x0 Would you guys mind taking a look over this and seeing if it works to merge? Especially a good time due to some of these queries that should/could be functional with newly released Azure Sentinel.  For example -

**Sigma** 
(Example: python3 tools/sigmac rules/windows/process_creation/win_susp_run_locations.yml -t ala):
```
SecurityEvent | where EventID == 4688 | where CommandLine contains ":\\RECYCLER\\" or CommandLine contains ":\\SystemVolumeInformation\\" or CommandLine startswith "%windir%\\Tasks\\" or CommandLine startswith "%systemroot%\\debug\\"
```

**Sentinel** 
(Source: https://github.com/Azure/Azure-Sentinel/blob/fc62e911b9c1c42a45a4f1f1bac1c861a00f7884/Detections/SecurityEvent/malware_in_recyclebin.txt):
```
let ProcessCreationEvents=() {
let processEvents=SecurityEvent
| where EventID==4688
| project  TimeGenerated, ComputerName=Computer,AccountName=SubjectUserName,        AccountDomain=SubjectDomainName,
FileName=tostring(split(NewProcessName, '\\')[-1]),
ProcessCommandLine = CommandLine, 
InitiatingProcessFileName=ParentProcessName,InitiatingProcessCommandLine="",InitiatingProcessParentFileName="";
processEvents};
ProcessCreationEvents 
| where FileName in~('cmd.exe','ftp.exe','schtasks.exe','powershell.exe','rundll32.exe','regsvr32.exe','msiexec.exe')
| where ProcessCommandLine contains ":\\recycler"
| project TimeGenerated, ComputerName, ProcessCommandLine, InitiatingProcessFileName
```

**Comment by thomaspatzke** [comment]
Nice contribution, @tuckner! I will integrate it in the next days!

**Comment by thomaspatzke** [comment]
Integrated it into master and added a *sysmon* backend option (`-Osysmon`) for generation of Sysmon event matching. Please review, @tuckner, for me it seems working as expected.

**Comment by tuckner** [comment]
Looks good!

**Pull request merged**
