### PR TITLE
[OSCD] Detects Obfuscated Powershell via use MSHTA in Scripts #31 (process_creation) 

### PR DESCRIPTION
**Pull request by NikitaStormwind**
Made it a single regular expression.

### CODE REVIEW

**Comment by zinint** [comment]
Hello again, @NikitaStormwind (:
I will check the rules and will get back to you, but straight away, can you please add [OSCD] prefix to your PR name?

**Comment by NikitaStormwind** [comment]
> Hello again, @NikitaStormwind (:
> I will check the rules and will get back to you, but straight away, can you please add [OSCD] prefix to your PR name?

Oh sure) I forgot)

**Comment by zinint** [comment]
Issue #1009 (useful link to see this PR in the Issue)))

Because our goal is to detect the obfuscation method looking for similar patterns in all of it obfuscation examples, I'd suggest dropping `downloadstring` & `powershell`, and focus on other patterns. Your regex, as a result, could look smth like this:
``` REGEX
(?i).*(set).*(&&).*(mshta).*(vbscript:createobject).*(\.run).*\(window\.close\).*"
```  

More to the point, because **one obfuscation method = 3 Sigma rules** (see the end of the Issue) can you please be so kind and create the 3rd rule for service creation events for that Task?

**Comment by NikitaStormwind** [comment]
> Issue #1009 (useful link to see this PR in the Issue)))
> 
> Because our goal is to detect the obfuscation method looking for similar patterns in all of it obfuscation examples, I'd suggest dropping `downloadstring` & `powershell`, and focus on other patterns. Your regex, as a result, could look smth like this:
> 
> ```regexp
> (?i).*(set).*(&&).*(mshta).*(vbscript:createobject).*(\.run).*\(window\.close\).*"
> ```
> 
> More to the point, because **one obfuscation method = 3 Sigma rules** (see the end of the Issue) can you please be so kind and create the 3rd rule for service creation events for that Task?

Ok, no problem. Tomorrow I'll edit the rule and create a third Sigma rule

**Comment by zinint** [comment]
That'll be super cool! Thanks again and have a nice evening!

**Comment by NikitaStormwind** [comment]
> > Issue #1009 (useful link to see this PR in the Issue)))
> > Because our goal is to detect the obfuscation method looking for similar patterns in all of it obfuscation examples, I'd suggest dropping `downloadstring` & `powershell`, and focus on other patterns. Your regex, as a result, could look smth like this:
> > ```regexp
> > (?i).*(set).*(&&).*(mshta).*(vbscript:createobject).*(\.run).*\(window\.close\).*"
> > ```
> > 
> > 
> > More to the point, because **one obfuscation method = 3 Sigma rules** (see the end of the Issue) can you please be so kind and create the 3rd rule for service creation events for that Task?
> 
> Ok, no problem. Tomorrow I'll edit the rule and create a third Sigma rule

Done

**Comment by yugoslavskiy** [comment]
Hello @NikitaStormwind! Well done!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
