### PR TITLE
[OSCD] Add Failed Authentication with Fake Account rule

### PR DESCRIPTION
**Pull request by ryanplasma**
Page 16 from #574

### CODE REVIEW

**Comment by aw350m33d** [comment]
Ryan I think that in general the rule can be merged. 

However, I would like the search identifiers to have clearer names. I know that many of the rules use different variations of the word `selection`. But I believe that for better readability, we need to give more descriptive names, such as `failed_login` or something like that. This will make it easier and faster for readers to understand the idea of your detect.

Could you give more descriptive names to search IDs?

**Comment by yugoslavskiy** [comment]
Hello @ryanplasma ! 

As for me, the rule looks perfect (: It's up to you to change the `selection`'s to more readable ones, but as most of the rules have pretty much the same approach as your one, I don't think that it is critical. So it's up to you to make changes before the merge. 

Thank you very much for your contribution!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Comment by ryanplasma** [comment]
I took a stab at giving them more descriptive names as I agree that it helps get some context on what it's doing.  Let me know if any of them aren't accurate.

**Comment by aw350m33d** [comment]
Awesome! 
With such names it's much clearer. Ryan thank you very much for your understanding and great desire to make high-quality rules right away!

**Comment by aw350m33d** [comment]
Hello Thomas (@thomaspatzke)! Thanks for the detailed feedback. When we discussed the rules for the deceptive-like approach, we also could not give a confident answer that such rules are needed by the users of the repository.

Personally, I like the general idea of ​​creating a set of rules for the deception-like approach. Well, I just would be interested in doing something like that. I'm not very familiar with the current advances in this area, but it seems to me that these kinds of detections require two types of entities: detection rules and scripts that will automatically prepare the infrastructure for such rules to work. Writing these scripts is a separate topic. But for describing detections, the Sigma syntax (and the very concept of a unified language for describing detections) is potentially very good.

I'm not saying that we need to include the rules for such an approach in the repository, but I would be interested to know your opinion on how Sigma (taking into account the roadmap and development plans in the medium term) could fit the described approach?

**Comment by ryanplasma** [comment]
I can either move this to unsupported or close out the PR - up to you all.

**Comment by aw350m33d** [comment]
Ryan, I'm sorry it took so long to answer. Then I suggest closing this pull request. I like the idea of your approach. Maybe look for open source projects in the field of deception that will benefit from your idea?

**Pull request closed without merging**
