### PR TITLE
[OSCD] Created powershell_suspicious_mounted_share_deletion.yml

### PR DESCRIPTION
**Pull request by svch0stz**
OSCD Sprint 2 Atomic Red Team Windows - https://github.com/Neo23x0/sigma/issues/1013 item 6 - T1070.005: Network Share Connection Removal (one process_creation rule and one PowerShell rule)

Sigmac Test:
`❯ python .\sigmac -t splunk -c .\config\splunk-windows.yml ..\rules\windows\powershell\powershell_suspicious_mounted_share_deletion.yml
(source="WinEventLog:Microsoft-Windows-PowerShell/Operational" EventCode="4104" (ScriptBlockText="*Remove-SmbShare*" OR ScriptBlockText="*Remove-FileShare*"))`

Should we add an `atomic` tag somewhere maybe?

### CODE REVIEW

**Comment by zinint** [comment]
Hello, @svch0stz! Welcome and thanks for your participation!
The rule seems spot-on for ART T1070.005, would you consider trying to create a [Rule Collection](https://github.com/Neo23x0/sigma/wiki/Specification#rule-collections) with your [2nd rule](https://github.com/Neo23x0/sigma/pull/1061/files) for the same test? E.g.
>     1. A global action document that defines common metadata.
>     2. The Security/4688 rule with all event details.
>     3. A repeat action document that replaces the logsource and EventID from the rule defined in 2.

**Comment by zinint** [comment]
Hello, @svch0stz! Welcome and thanks for your participation!
The rule seems spot-on for ART T1070.005.

**Comment by zinint** [comment]
I think it's ready to be merged! @yugoslavskiy

**Comment by yugoslavskiy** [comment]
Thank you, @svch0stz ! Well done (:

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
