### PR TITLE
[OSCD] Windows - Suspicious Service DACL Modification

### PR DESCRIPTION
**Pull request by w0rk3r**

### CODE REVIEW

**Comment by aw350m33d** [comment]
Hi Jonhnathan! 
It seems that you accidentally deleted one of the rules (`rules/windows/process_creation/win_susp_replace_lolbin.yml`). This is the rule you suggested in PR https://github.com/Neo23x0/sigma/pull/1072. Apparently, there is some problem with the commit history.

Could you check it out?

**Comment by w0rk3r** [comment]
Forgot it got merged, I was doing it for every PR, fixed on this one

**Comment by aw350m33d** [comment]
In general, I have no questions about the rule. Only missing the value of `oscd.community` in the author field.

**Comment by w0rk3r** [comment]
Fixed!

**Comment by aw350m33d** [comment]
Perfectly! I believe that this rule can be merged. @yugoslavskiy

**Comment by yugoslavskiy** [comment]
The rule looks perfect! Thank you very much, @w0rk3r!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
