### PR TITLE
[OSCD] Create win_susp_mounted_share_deletion.yml

### PR DESCRIPTION
**Pull request by svch0stz**
OSCD Sprint 2 Atomic Red Team Windows - #1013 item 6 - T1070.005: Network Share Connection Removal (one process_creation rule and one PowerShell rule)

Sigmac Test:
`❯ python .\sigmac -t splunk -c .\config\splunk-windows.yml ..\rules\windows\process_creation\win_susp_mounted_share_deletion.yml
((Image="*\\net.exe" OR Image="*\\net1.exe") (CommandLine="*/delete*"))`

### CODE REVIEW

**Comment by zinint** [comment]
Hello again, @svch0stz (: (left a comment in your 2nd related PR #1060)
image

**Comment by zinint** [comment]
> 
> 
> Hello again, @svch0stz (: (left a comment in your 2nd related PR #1060)
> image

Following up my screenshot before, I ran a couple of tests, and I would suggest changing your current `Image` condition to smth like this:
``` YAML
ParentImage|endswith: 'net.exe'
Image|endswith: '\net1.exe'
```
What do you think?

**Comment by svch0stz** [comment]
@zinint that looks good to me! think that's more thorough.

Could also add 5144 too?

image

**Comment by svch0stz** [comment]
@zinint Will update now :)

**Comment by yugoslavskiy** [comment]
Hello @svch0stz ! The rule looks perfect (: Thank you for your contribution!

**Review by yugoslavskiy — APPROVED** [review]
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

**Pull request merged**
