### PR TITLE
Cmd.exe Path Traversal Detection / Argument Spoofing

### PR DESCRIPTION
**Pull request by Iveco**
Cmd.exe Path Traversal Detection / Argument Spoofing

### CODE REVIEW

**Comment by Neo23x0** [comment]
Why should the CommandLine and the ParentCommandLine contain `../../`?

**Comment by Iveco** [comment]
grafik

**Comment by Iveco** [comment]
To help reduce noise

**Comment by Iveco** [comment]
I removed the field as suggested and the PR is green now. Sorry for that ;-)

**Pull request merged**
