### PR TITLE
modifying couple of rules

### PR DESCRIPTION
**Pull request by omkar72**
Addition based on recent threat reports

### CODE REVIEW

**Comment by omkar72** [comment]
Need help here to understand why commits are failing for elasticsearch strings.

**Comment by omkar72** [comment]
@thomaspatzke @Neo23x0  - Any suggestion here would help on why these failed ?

**Comment by thomaspatzke** [comment]
This happens likely because the pull request is based on an older version of the master branch. The ES tests started to fail after a while and I've removed them from the tests. Rebase your work to the current master to get rid of the errors.

**Comment by omkar72** [comment]
Thanks @thomaspatzke

**Pull request merged**
