### PR TITLE
Improved Microsoft ATP mapping, using Advanced Hunting Schema

### PR DESCRIPTION
**Pull request by wietze**
See https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-schema-reference for full scheme and details.

### CODE REVIEW

**Comment by wietze** [comment]
Can't work out why the CI keeps failing, if there is something I should change please let me know.

**Comment by Neo23x0** [comment]
I cannot find the issue. @thomaspatzke, could you look for the problem?

**Comment by wietze** [comment]
@thomaspatzke any luck?

**Comment by thomaspatzke** [comment]
CI tests fail because the code coverage drops below 90%. I try to fix this.

**Comment by thomaspatzke** [comment]
Done, tests are running. Will merge soon.

**Comment by thomaspatzke** [comment]
Merged! Thanks for the PR and sorry for the delay.

**Pull request merged**
