### PR TITLE
 Rule Windows 10 scheduled task SandboxEscaper 0-day

### PR DESCRIPTION
**Pull request by olafhartong**

### CODE REVIEW

**Comment by Neo23x0** [comment]
Ah, the tests failed because this rule should be a "process creation" rule. I'll fix that.

**Comment by olafhartong** [comment]
haha sorry, haven't been fully adjusted to the new schema. thanks

**Comment by Neo23x0** [comment]
We should add the password switch "/RP" as well. The more exact the better.

**Comment by olafhartong** [comment]
fair point, agreed

**Pull request merged**
